spring.application.name=students_db
spring.datasource.url=jdbc:postgresql://localhost:5432/students_db
spring.datasource.username=nuby
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate=WARN

management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
